# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
executors:
  # https://circleci.com/docs/docker-compose/#using-docker-compose-with-machine-executor
  # here we can define an executor that will be shared across different jobs
  dck-executor:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
      resource_class: medium
    # docker:
    # - image: cimg/base:current

jobs:
  install:
    executor: dck-executor
    steps:
    # - setup_remote_docker
    - checkout
    # Download and cache dependencies
    - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "backend/poetry.lock" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
    - run:
        name: Build docker & installation of dependencies
        command: make setup
    - save_cache:
          paths:
              - ./backend/.venv
          key: v1-dependencies-{{ checksum "backend/poetry.lock" }}
  unit-tests:
      executor: dck-executor
      steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "backend/poetry.lock" }}
          - run:
              name: Force recreation of .env
              command: make _env
          - run:
                name: Run unit tests
                command: make test
  check-format:
      executor: dck-executor
      steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "backend/poetry.lock" }}
          - run:
              name: Force recreation of .env
              command: make _env
          - run:
                name: Run check_format
                command: make check_format
  check-linting:
      executor: dck-executor
      steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "backend/poetry.lock" }}
          - run:
              name: Force recreation of .env
              command: make _env
          - run:
                name: Run check_linting
                command: make check_linting

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  develop-PR:
    jobs:
      - install
      - unit-tests:
            requires:
                - install
      - check-linting:
            requires:
                - install
      - check-format:
            requires:
                - install
